version: "3.2"

services:
  vote:
    image: rehzende/vote:latest
    build:
      context: ./vote
    command: python app.py
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    image: rehzende/result:latest
    build:
      context: ./result
    command: nodemon server.js
    environment:
      - PSQL_HOST=db
      - PSQL_PORT=5432
      - PSQL_USER=postgres
      - PSQL_PASSWORD=mysecretpassword
      - PSQL_DB=postgres
    ports:
      - "3200:80"
      - "5858:5858"
    links:
      - "db:db"
    networks:
      - front-tier
      - back-tier

  worker:
    image: rehzende/worker:latest
    build:
      context: ./worker
    environment:
      - PSQL_HOST=db
      - PSQL_PORT=5432
      - PSQL_USER=postgres
      - PSQL_PASSWORD=mysecretpassword
      - PSQL_DB=postgres
    depends_on:
      - "redis"
    networks:
      - back-tier

  redis:
    image: redis:alpine
    ports: ["6379"]
    networks:
      - back-tier

  db:
    image: postgres:9.4
    networks:
      - back-tier
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

networks:
  front-tier:
  back-tier: